### ISSUE TITLE
[BUG] - bot abre e fecha 

### ISSUE THREAD

**Issue by magriNbh** [lucasmonstro/pytibia#3]
Instalei todos os requirements corretamente, porém quando abro o bot ocorre este erro: 
![image](https://user-images.githubusercontent.com/100314235/156992141-f05bad66-176e-405e-934d-c3d27d8195b8.png)

sabe como resolver ?

**Comment by magriNbh** [comment]
consegui resolver o primeiro erro, agora quando abro o bot ele fica somente nessa tela:
![image](https://user-images.githubusercontent.com/100314235/156993390-fb70956c-7ca8-472c-a91f-a12a02a134df.png)

como configuro o bot ?

**Comment by lucasmonstro** [comment]
Salve, infelizmente o bot está incompleto e atualmente funcionando como um SDK. Brevemente vou colocar uma UI com várias ações disponíveis.

**Comment by lucasmonstro** [comment]
Salve, retomei o dev do projeto para tentar fazer um MVP. Tem interesse em ajudar?

**Comment by leleuvilela** [comment]
Assim, eu literalmente fiz um post falando que tenho interesse em ajudar kk

**Comment by lucasmonstro** [comment]
@leleuvilela te respondi lá, tinha esquecido de responder rs

**Comment by lucasmonstro** [comment]
@magriNbh ainda precisa de ajuda? Retomamos com o dev do bot recentemente.
