### ISSUE TITLE
Contribuindo com o projeto.

### ISSUE THREAD

**Issue by leleuvilela** [lucasmonstro/pytibia#4]
Olá :)

Então, como programador (e jogador de tibia) tenho muito entusiasmo em ajudar no projeto.
Mas mexendo nele por alguns minutos, não consegui fazer ele funcionar, a não fazer uma captura da tela pelo OBS e capturando a tela do OBS, mas mesmo assim não tive tanto sucesso.

Se puder me passar as configurações necessárias (resoluções da tela talvez?), ou como vocês faz para conseguir capturar a tela do Tibia, teria total prazer em contribuir para o projeto.

Abraço, valeu.

**Comment by lucasmonstro** [comment]
Oba. Pode me passar seu zap, ou linkedin? Valeu :)

**Comment by lucasmonstro** [comment]
@leleuvilela Will help project developing python stuffs.

**Comment by gabrielresende06** [comment]
O projeto é para rodar em windows?
ou roda em outros SO também?
