### ISSUE TITLE
[BUG] - Cannot get target creature when it is in black life

### ISSUE THREAD

**Issue by eusolobehe1898** [lucasmonstro/PyTibia#57]
**Describe the bug**

Sometimes the char doesn't detect the target creature when it's in black life, so the char stops following the creature and stays still without moving.

**To Reproduce**
Attacking a creature that runs away and expects it to stay in black life.

**Expected behavior**
I want the char to keep following the creature.

**Screenshots**
![image](https://user-images.githubusercontent.com/93688664/234411239-89c58a33-ce03-475a-ba24-eae58a4ea032.png)

**Desktop (please complete the following information):**
 - OS: windows 7
 - Tibia Version [13.x]

**Comment by lucasmonstro** [comment]
Was fixed in commit https://github.com/lucasmonstro/PyTibia/commit/fbb74e80762b361b74b16e8ab79656dd9c9f5fe3. There was a performance bug to reduce the quadratic complexity of the algorithm.

Thanks @eusolobehe1898
